Dockerfile using debug or release binaries

diff --git a/test_env/Dockerfile.client b/test_env/Dockerfile.client
--- a/test_env/Dockerfile.client
+++ b/test_env/Dockerfile.client
@@ -9,11 +9,15 @@ ENV RUST_LOG=$RUST_LOG
 RUN apt update \
     && apt install -y iputils-ping dnsutils iproute2
 
-COPY ./target/release /app
+# Copy debug or release (prefered) build
+COPY ./target/debu[g]/example[s]/http_clien[t] /app/
+COPY ./target/releas[e]/example[s]/http_clien[t] /app/
+RUN test -f /app/http_client || err "Failed to find http_client bin"
+
 CMD export SERVER_IP=$(dig +short relay_server -t a) \
     && echo $SERVER_IP \
     && tc qdisc add dev eth0 root netem delay $LATENCY \
-    && /app/examples/http_client \
+    && /app/http_client \
     --api-port 8081 \
     --relay-addr tcp://$SERVER_IP:7464 \
     --p2p-bind-addr tcp://0.0.0.0:9081
diff --git a/test_env/Dockerfile.server b/test_env/Dockerfile.server
--- a/test_env/Dockerfile.server
+++ b/test_env/Dockerfile.server
@@ -14,7 +14,11 @@ EXPOSE 7465/udp
 RUN apt update \
     && apt install -y iproute2 iputils-ping
 
-COPY ./target/release /app
+# Copy debug or release (prefered) build
+COPY ./target/debu[g]/ya-relay-serve[r] /app/
+COPY ./target/releas[e]/ya-relay-serve[r] /app/
+RUN test -f /app/ya-relay-server || err "Failed to find ya-relay-server bin"
+
 CMD tc qdisc add dev eth0 root netem delay $LATENCY \
     && /app/ya-relay-server \
     -a tcp://0.0.0.0:7464 \
